# syntax=docker/dockerfile:1
FROM node:20-slim AS base
WORKDIR /app

# Install deps
COPY package.json yarn.lock /app/
RUN yarn install --frozen-lockfile

# Build
COPY . /app
RUN yarn run build

EXPOSE 3000
ENV PORT=3000
CMD ["yarn", "start", "-H", "0.0.0.0", "-p", "3000"]
